# example
# # prometheus-playbook  blackbox.yaml

- name: install prometheus blackbox_exporter
  hosts: dev
  strategy: free
  remote_user: root
  gather_facts: true
  vars:
  vars_files:
    - vars/all.yml
    - vars/blackbox.yml
  roles:
    - blackbox
