---
# file: handlers/main.yml
#


- name: reload systemd node_exporter
  systemd:
    name: node_exporter
    state: reloaded
    daemon_reload: True

- name: start systemd node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: True

- name: restart systemd node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: True

- name: start service node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: restart service node_exporter
  service:
    name: node_exporter
    state: restarted

- name: reload service node_exporter
  service:
    name: node_exporter
    state: reloaded
