---
# file: tasks/main.yml
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include: preinstall-init.yml
- include: install-gosu.yml
- include: install-node-exporter.yml
