---
# file: handlers/main.yml
#

- name: reload systemd blackbox
  systemd:
    name: blackbox_exporter
    state: reloaded
    daemon_reload: True

- name: start systemd blackbox
  systemd:
    name: blackbox_exporter
    state: started
    enabled: true
    daemon_reload: True

- name: restart systemd blackbox
  systemd:
    name: blackbox_exporter
    state: restarted
    daemon_reload: True

- name: start service blackbox
  service:
    name: blackbox_exporter
    state: started
    enabled: yes

- name: restart service blackbox
  service:
    name: blackbox_exporter
    state: restarted

- name: reload service blackbox
  service:
    name: blackbox_exporter
    state: reloaded
